#+title: Evolab
#+author: Iannis Zannos, Emmanouel Rovithis

last updated: 24/12/25

* Γενική Περιγραφή (Γενική Description)

** ελλ

Η εργασία εξαμήνου για την τάξη 2025-2026 του μαθήματος AUD722 είναι συλλογική. Οι φοιτητές/τριες θα δημιουργήσουν την πολυκαναλική ηχητική εγκατάσταση "Evolab" με ήχους σχεδιασμένους και προγραμματισμένους από τους ίδιους/ες στο SuperCollider. Η προγραμματιστική/καλλιτεχνική συμβολή κάθε φοιτητή/τριας στο έργο και η γενική συμμετοχή τους κατά τη διάρκεια του εξαμήνου θα καθορίσουν τον τελικό τους βαθμό.

Η ηχητική εγκατάσταση αναπαριστά ένα δυναμικό ηχητικό περιβάλλον, στο οποίο εκτελούνται διάφορες διεργασίες που ονομάζονται ηχητικά πλάσματα. Κάθε ηχητικό πλάσμα παράγει ήχο σύμφωνα με αλγόριθμους (προγράμματα) που ονομάζονται συμπεριφορές. Κάθε φοιτητής/τρια είναι υπεύθυνος/η για τη δημιουργία ενός ηχητικού πλάσματος και των συμπεριφορών του.

Το περιβάλλον εκπέμπει διάφορες καταστάσεις. Κάθε κατάσταση είναι ένας αλγόριθμος που παράγει τις παραμέτρους εισόδου, οι οποίες επηρεάζουν τις συμπεριφορές όλων των ηχητικών πλασμάτων. 

** eng

The semester project for the 2025-2026 AUD722 class is collective. The students will create the multichannel sound installation "EvoLab" featuring sounds designed and programmed by themselves in SuperCollider. The students' programming/artistic contribution to the project and their general participation throughout the semester will define their final grade.

The sound installation represents a dynamic audio environment in which several processes run, which are called sound creatures. Each sound creature produces sound according to algorithms (programs) called behaviors. Each student is responsible for creating one sound creature and its behaviors.  

The environment transmits different states. Each state is an algorithm producing input parameters that affect the behaviors of all sound creatures.


* Ηχητικό Πλάσμα (Sound Creature)

** ελλ
Κάθε Ηχητικό Πλάσμα αποτελείται από το Σώμα και την Ψυχή. Το Σώμα είναι ένα ηχητικό δείγμα από τον πραγματικό κόσμο, ενώ η Ψυχή μια ταλάντωση που δε συναντάται στο φυσικό ακουστικό περιβάλλον.

Ως εκ τούτου, κάθε φοιτητής/τρια ξεκινάει τον κώδικά του/της εισάγοντας:

α. ένα αρχείο .wav διάρκειας 3 έως 5 δευτερολέπτων
β. μία γεννήτρια ταλάντωσης στη συχνότητα που επιθυμεί

Έπειτα:
γ. η σύνδεση ανάμεσα σε Σώμα και Ψυχή γίνεται μέσω Ring Modulation.
δ. το σχήμα του Ηχητικού Πλάσματος διαμορφώνεται από Amplitude Envelope.

Τα υπόλοιπα χαρακτηριστικά του Ηχητικού Πλάσματος υπόκεινται στη φαντασία κάθε συμμετέχοντα/ουσας δημιουργού. 


** eng
Each Sound Creature consists of the Body and the Soul. The Body is an audio sample from the real world, while the Soul is an oscillation not found in the natural acoustic environment.

Therefore, each student starts their code by entering:

a. a .wav file lasting 3 to 5 seconds
b. an oscillation generator at the desired frequency

Then:
c. the connection between Body and Soul is made through Ring Modulation.
d. the shape of the Sound Creature is formed by Amplitude Envelope.

The remaining characteristics of the Sound Creature are subject to the imagination of each participating creator.


* Καταστάσεις Περιβάλλοντος (Environment States)

** ελλ
Οι παρακάτω περιοδικές Καταστάσεις επηρεάζουν τον Κιρκάδιο Ρυθμό κάθε Ηχητικού Πλάσματος:
1. αυγή
2. ημέρα
3. σούρουπο
4. νύχτα

Mη-περιοδικά προκύπτει η Κατάσταση:
5. Κίνδυνος

** eng
The following periodic states affect the Circadian rhythm of Every Sound Creature:
1. dawn
2. day
3. dusk
4. night

Non-periodically occurs the State:
2. Danger

