#+title: Evolab
#+author: Iannis Zannos, Emmanouel Rovithis

last updated: 24/12/25

* Γενική Περιγραφή (Γενική Description)

** ελλ

Η εργασία εξαμήνου για την τάξη 2025-2026 του μαθήματος AUD722 είναι συλλογική. Οι φοιτητές/τριες θα δημιουργήσουν την πολυκαναλική ηχητική εγκατάσταση "EvoLab" με ήχους σχεδιασμένους και προγραμματισμένους από τους ίδιους/ες στο SuperCollider. Η προγραμματιστική/καλλιτεχνική συμβολή κάθε φοιτητή/τριας στο έργο και η γενική συμμετοχή τους κατά τη διάρκεια του εξαμήνου θα καθορίσουν τον τελικό τους βαθμό.

Η ηχητική εγκατάσταση αναπαριστά ένα δυναμικό ηχητικό περιβάλλον, στο οποίο δρουν πλάσματα παράγοντας ήχους. Ο κάθε ένας φοιτητής σχεδιάζει από ένα πλάσμα. Κάθε ηχητικό πλάσμα παράγει ήχο σύμφωνα με αλγόριθμους (προγράμματα) που ονομάζονται συμπεριφορές. Κάθε φοιτητής/τρια είναι υπεύθυνος/η για τη δημιουργία ενός ηχητικού πλάσματος και των συμπεριφορών του.  Το πλάσμα του κάθε φοιτητή αλλάζει συμπεριφορά απαντώντας σε μηνύματα που δέχεται από το περιβάλλον.  Το περιβάλλον υλοποιείται στο πρότυπο (class) EvoLab.  Κατά την διάρκεια της εγκατάστασης, το EvoLab εκπέμπει διαδοχικά σε τακτά διαστήματα τα μηνύματα στα οποία απαντούν τα πλάσματα των φοιτητών. Οι φοιτητές καλούνται να προγραμματίσουν τους αλγόριθμους με τους οποίους το πλάσμα τους απαντά στα μηνύματα από το περιβάλλον.  Ορίζουμε αρχικά μόνο δύο μηνύματα/καταστάσεις: ημέρα (day) και νύχτα (night).  Αντίστοιχα ο κάθε φοιτητής πρέπει να προγραμματίσει 2 μεθόδους με τα ονόματα αυτά, που παράγουν διαφορετικούς ήχους που αντιστοιχούν στις έννοιες της ημέρας και της νύχτας σύμφωνα με την κρίση του φοιτητή.

Ο κώδικας για τον σχεδιασμό και τις δοκιμές των πλασμάτων βρίσκονται στο αποθετήριο https://github.com/iani/AUD722_CreatureProject. Δείτε περισσότερες οδηγίες στο αρχείο README.org του αποθετηρίου αυτού. 

** eng

The semester project for the 2025–2026 class of course AUD722 is collaborative. Students create a multichannel sound installation called “EvoLab” using sounds that they themselves design and program in SuperCollider. The programming/artistic contribution of each student to the project, as well as their overall participation throughout the semester, will determine their final grade.

The sound installation represents a dynamic sonic environment in which there act creature entities that produce sound. Each student designs one sound-generatig creature. Each sound creature produces sound according to algorithms (programs) called behaviors. Each student is responsible for creating one sound creature and its behaviors. The creature created by each student changes its behavior in response to messages it receives from the environment. The environment is implemented in the class EvoLab. During the installation, EvoLab sequentially emits, at regular intervals, the messages to which the students’ creatures respond. Students are required to program the algorithms by which their creature responds to messages from the environment. Initially, only two messages/states are defined: day and night. Accordingly, each student must program two methods with these names, producing different sounds that correspond to the concepts of day and night, according to the student’s own judgment.

The code for the design and testing of the creatures is located in the repository https://github.com/iani/AUD722_CreatureProject. See further instructions in the README.org file of this repository.

* Ηχητικό Πλάσμα (Sound Creature)

** ελλ
Κάθε Ηχητικό Πλάσμα αποτελείται από το Σώμα και την Ψυχή. Το Σώμα είναι ένα ηχητικό δείγμα από τον πραγματικό κόσμο, ενώ η Ψυχή μια ταλάντωση που δε συναντάται στο φυσικό ακουστικό περιβάλλον.

Ως εκ τούτου, κάθε φοιτητής/τρια ξεκινάει τον κώδικά του/της εισάγοντας:

α. ένα αρχείο .wav διάρκειας 3 έως 5 δευτερολέπτων
β. μία γεννήτρια ταλάντωσης στη συχνότητα που επιθυμεί

Έπειτα:
γ. η σύνδεση ανάμεσα σε Σώμα και Ψυχή γίνεται μέσω Ring Modulation.
δ. το σχήμα του Ηχητικού Πλάσματος διαμορφώνεται από Amplitude Envelope.

Τα υπόλοιπα χαρακτηριστικά του Ηχητικού Πλάσματος υπόκεινται στη φαντασία κάθε συμμετέχοντα/ουσας δημιουργού. 


** eng
Each Sound Creature consists of the Body and the Soul. The Body is an audio sample from the real world, while the Soul is an oscillation not found in the natural acoustic environment.

Therefore, each student starts their code by entering:

a. a .wav file lasting 3 to 5 seconds
b. an oscillation generator at the desired frequency

Then:
c. the connection between Body and Soul is made through Ring Modulation.
d. the shape of the Sound Creature is formed by Amplitude Envelope.

The remaining characteristics of the Sound Creature are subject to the imagination of each participating creator.


* Καταστάσεις Περιβάλλοντος (Environment States)

** ελλ
Οι παρακάτω περιοδικές Καταστάσεις επηρεάζουν τον Κιρκάδιο Ρυθμό κάθε Ηχητικού Πλάσματος:
1. αυγή
2. ημέρα
3. σούρουπο
4. νύχτα

Mη-περιοδικά προκύπτει η Κατάσταση:
5. Κίνδυνος

** eng
The following periodic states affect the Circadian rhythm of Every Sound Creature:
1. dawn
2. day
3. dusk
4. night

Non-periodically occurs the State:
2. Danger

